use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use anyhow::{Context, Result};

pub struct FixerEngine;

impl FixerEngine {
    /// Generates or updates .claudeignore and .cursorignore in the target repository
    pub fn generate_ignore_files(root: &Path) -> Result<Vec<PathBuf>> {
        let canonical_root = root.canonicalize().unwrap_or_else(|_| root.to_path_buf());
        let mut created = Vec::new();

        let ignore_content = r#"# Generated by agentprof (AI Agent Workspace Optimizer)
# Prevents agent search tools from indexing massive build directories and leaking secrets

# === Secrets & Sensitive Files ===
.env
.env.*
!.env.example
*.pem
*.key
id_rsa
id_ed25519
credentials.json
service-account.json

# === Build Artifacts & Large Directories ===
# Swift / Apple / Xcode
.build/
DerivedData/
*.xcarchive/
*.dSYM/
*.xcodeproj/project.xcworkspace/xcuserdata/
*.xcodeproj/xcuserdata/

# Rust / Cargo
target/
Cargo.lock.bak

# Node.js / Web
node_modules/
.next/
dist/
out/
.turbo/
.cache/

# Python
__pycache__/
*.pyc
.venv/
venv/
.pytest_cache/
.mypy_cache/
.ruff_cache/

# Logs & Dumps
*.log
*.tmp
test_output.log
core.*
"#;

        let claudeignore = canonical_root.join(".claudeignore");
        let cursorignore = canonical_root.join(".cursorignore");

        fs::write(&claudeignore, ignore_content)
            .with_context(|| format!("Failed to write {}", claudeignore.display()))?;
        created.push(claudeignore);

        fs::write(&cursorignore, ignore_content)
            .with_context(|| format!("Failed to write {}", cursorignore.display()))?;
        created.push(cursorignore);

        Ok(created)
    }

    /// Injects an idempotent fast-path bypass guard into ~/.zshrc
    pub fn inject_shell_fast_path() -> Result<(PathBuf, bool)> {
        let home = std::env::var("HOME")
            .map(PathBuf::from)
            .context("HOME environment variable not set")?;
        let zshrc_path = home.join(".zshrc");

        if !zshrc_path.exists() {
            anyhow::bail!("~/.zshrc not found at {}", zshrc_path.display());
        }

        let existing_content = fs::read_to_string(&zshrc_path)?;

        if existing_content.contains("[agentprof]") || existing_content.contains("CLAUDE_CODE") {
            return Ok((zshrc_path, false)); // already installed
        }

        // Create backup
        let backup_path = home.join(".zshrc.agentprof.bak");
        fs::write(&backup_path, &existing_content)?;

        let fast_path_header = r#"# === [agentprof] Fast-Path Bypass for AI Agents & Subshells ===
if [[ $- != *i* || -n "$CLAUDE_CODE" || -n "$OPENCODE" || -n "$AI_AGENT" || -n "$CODEX" || -n "$CURSOR_AGENT" ]]; then
  # Preserve essential PATH additions
  export PATH="$HOME/.cargo/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"
  return 0 2>/dev/null || exit 0
fi
# === [agentprof] End Fast-Path ===

"#;

        let mut new_content = String::new();
        new_content.push_str(fast_path_header);
        new_content.push_str(&existing_content);

        fs::write(&zshrc_path, new_content)?;

        Ok((zshrc_path, true))
    }

    /// Compiles ~/.zshrc to bytecode using zcompile
    pub fn compile_zshrc_bytecode() -> Result<bool> {
        let home = std::env::var("HOME")
            .map(PathBuf::from)
            .context("HOME environment variable not set")?;
        let zshrc = home.join(".zshrc");
        if !zshrc.exists() {
            return Ok(false);
        }

        let status = Command::new("zsh")
            .args(["-c", "zcompile ~/.zshrc"])
            .status();

        Ok(status.map(|s| s.success()).unwrap_or(false))
    }
}
