use std::path::Path;
use anyhow::Result;
use serde::{Deserialize, Serialize};

use crate::core::mcp_profiler::McpProfiler;
use crate::core::scanner::InstructionScanner;
use crate::core::shell_bench::ShellBenchmarker;
use crate::core::workspace_guard::WorkspaceGuard;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkspaceHealthScore {
    pub score: usize,
    pub grade: &'static str,
    pub subshell_latency_score: usize,
    pub context_budget_score: usize,
    pub workspace_hygiene_score: usize,
    pub security_score: usize,
    pub summary_markdown: String,
}

pub struct ReportGenerator;

impl ReportGenerator {
    pub fn calculate_health_score(workspace_root: &Path) -> Result<WorkspaceHealthScore> {
        let context = InstructionScanner::scan_workspace(workspace_root)?;
        let bench = ShellBenchmarker::run_benchmark(3)?;
        let guard = WorkspaceGuard::audit(workspace_root)?;
        let mcp = McpProfiler::profile(workspace_root)?;

        let mut total_score = 100isize;

        // 1. Subshell latency deduction (max 25 points)
        let mut subshell_score = 25usize;
        if bench.interactive_login_ms > 300.0 {
            total_score -= 15;
            subshell_score = subshell_score.saturating_sub(15);
        } else if bench.interactive_login_ms > 100.0 {
            total_score -= 8;
            subshell_score = subshell_score.saturating_sub(8);
        }
        if !bench.has_agent_fast_path {
            total_score -= 10;
            subshell_score = subshell_score.saturating_sub(10);
        }

        // 2. Context budget deduction (max 25 points)
        let mut context_score = 25usize;
        if context.total_tokens_cl100k > 5000 {
            total_score -= 15;
            context_score = context_score.saturating_sub(15);
        } else if context.total_tokens_cl100k > 2000 {
            total_score -= 8;
            context_score = context_score.saturating_sub(8);
        }

        // 3. Workspace hygiene deduction (max 25 points)
        let mut hygiene_score = 25usize;
        let unignored_dirs = guard.total_unignored_heavy_dirs;
        if unignored_dirs > 0 {
            let penalty = (unignored_dirs * 8).min(20) as isize;
            total_score -= penalty;
            hygiene_score = hygiene_score.saturating_sub(penalty as usize);
        }
        if !guard.has_claudeignore {
            total_score -= 5;
            hygiene_score = hygiene_score.saturating_sub(5);
        }

        // 4. Security deduction (max 25 points)
        let mut security_score = 25usize;
        let exposed_secrets = guard.total_exposed_secrets;
        if exposed_secrets > 0 {
            let penalty = (exposed_secrets * 15).min(25) as isize;
            total_score -= penalty;
            security_score = security_score.saturating_sub(penalty as usize);
        }

        let final_score = total_score.clamp(0, 100) as usize;
        let grade = if final_score >= 90 {
            "A+ (Optimal)"
        } else if final_score >= 80 {
            "B (Good)"
        } else if final_score >= 65 {
            "C (Needs Optimization)"
        } else {
            "F (Critical Bottlenecks)"
        };

        let summary_markdown = format!(
            r#"### 🤖 AI Agent Workspace Health: **{}/100** ({})

| Category | Score | Status |
| :--- | :---: | :--- |
| **Subshell Spawn Latency** | {}/25 | `{:.1}ms` spawn overhead |
| **Context & Token Budget** | {}/25 | `{} tokens` total instructions |
| **Workspace Hygiene** | {}/25 | `{} unignored` heavy build folders |
| **Secret & Security Guard** | {}/25 | `{} exposed` credential/env files |
| **MCP Tool Schema Load** | — | `{} tokens` across {} servers |

*Generated by [agentprof](https://github.com/dautovri/agentprof)*
"#,
            final_score,
            grade,
            subshell_score,
            bench.interactive_login_ms,
            context_score,
            context.total_tokens_cl100k,
            hygiene_score,
            guard.total_unignored_heavy_dirs,
            security_score,
            guard.total_exposed_secrets,
            mcp.total_estimated_tokens,
            mcp.total_servers,
        );

        Ok(WorkspaceHealthScore {
            score: final_score,
            grade,
            subshell_latency_score: subshell_score,
            context_budget_score: context_score,
            workspace_hygiene_score: hygiene_score,
            security_score,
            summary_markdown,
        })
    }
}
