#!/usr/bin/env bash
# Writes a Homebrew formula that installs the prebuilt release binaries, using
# the .sha256 files produced by the release workflow.
#   scripts/homebrew-formula.sh v0.3.0 dist/ > agentprof.rb
set -euo pipefail

tag="${1:?usage: homebrew-formula.sh <tag> <dist-dir>}"
dist="${2:?usage: homebrew-formula.sh <tag> <dist-dir>}"
version="${tag#v}"
repo="${AGENTPROF_REPO:-dautovri/agentprof}"
base="https://github.com/$repo/releases/download/$tag"

sha() {
  local file="$dist/$1.tar.gz.sha256"
  [ -f "$file" ] || { echo "missing $file" >&2; exit 1; }
  awk '{print $1}' "$file"
}

# Resolved up front: a failure inside the heredoc below would not stop the script.
darwin_arm64="$(sha agentprof-darwin-arm64)"
darwin_x86_64="$(sha agentprof-darwin-x86_64)"
linux_arm64="$(sha agentprof-linux-arm64)"
linux_x86_64="$(sha agentprof-linux-x86_64)"

cat <<RUBY
# Generated by scripts/homebrew-formula.sh for $tag. Do not edit by hand.
class Agentprof < Formula
  desc "Measure and fix what slows AI coding agents down"
  homepage "https://github.com/$repo"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/agentprof-darwin-arm64.tar.gz"
      sha256 "$darwin_arm64"
    end
    on_intel do
      url "$base/agentprof-darwin-x86_64.tar.gz"
      sha256 "$darwin_x86_64"
    end
  end

  on_linux do
    on_arm do
      url "$base/agentprof-linux-arm64.tar.gz"
      sha256 "$linux_arm64"
    end
    on_intel do
      url "$base/agentprof-linux-x86_64.tar.gz"
      sha256 "$linux_x86_64"
    end
  end

  def install
    bin.install "agentprof"
    generate_completions_from_executable(bin/"agentprof", "completions")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentprof --version")
    assert_match "scan", shell_output("#{bin}/agentprof --help")
  end
end
RUBY
